export const CANDIDATE_VERIFICATION_SCRIPT = "verify:candidate";
export const CANDIDATE_VERIFICATION_COMMAND = `npm run ${CANDIDATE_VERIFICATION_SCRIPT}`;
export const CANDIDATE_VERIFICATION_ARGS = ["run", CANDIDATE_VERIFICATION_SCRIPT] as const;
